name: my_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - brotli=1.2.0=hca488c2_0
  - brotli-bin=1.2.0=hce9b42c_0
  - brotli-python=1.2.0=py311h69b7e7c_0
  - bzip2=1.0.8=h80987f9_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - certifi=2025.10.5=pyhd8ed1ab_0
  - cffi=1.17.1=py311h3a79f62_0
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - contourpy=1.3.3=py311h57a9ea7_2
  - cpuonly=2.0=0
  - cycler=0.12.1=pyhd8ed1ab_1
  - expat=2.7.1=h313beb8_0
  - filelock=3.17.0=py311hca03da5_0
  - fonttools=4.60.1=py311ha9b3269_0
  - freetype=2.14.1=hce30654_0
  - gmp=6.3.0=h313beb8_0
  - gmpy2=2.2.1=py311h5c1b81f_0
  - h2=4.3.0=pyhcf101f3_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - jinja2=3.1.6=py311hca03da5_0
  - kiwisolver=1.4.9=py311h63e5c0c_1
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libblas=3.9.0=38_h51639a9_openblas
  - libbrotlicommon=1.2.0=h87ba0bc_0
  - libbrotlidec=1.2.0=h95a88de_0
  - libbrotlienc=1.2.0=hb1b9735_0
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=20.1.8=hd7fd590_1
  - libdeflate=1.22=hd74edd7_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.4.4=hca03da5_1
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - libopenblas=0.3.30=openmp_ha158390_3
  - libpng=1.6.50=h280e0eb_1
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.0=hfce79cd_1
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libzlib=1.3.1=h5f15de7_0
  - llvm-openmp=21.1.4=h4a912ad_0
  - markupsafe=3.0.2=py311h80987f9_0
  - matplotlib=3.10.7=py311ha1ab1f8_0
  - matplotlib-base=3.10.7=py311h29553df_0
  - mpc=1.3.1=h80987f9_0
  - mpfr=4.2.1=h80987f9_0
  - mpmath=1.3.0=py311hca03da5_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - ncurses=6.5=hee39554_0
  - networkx=3.5=py311hca03da5_0
  - openjpeg=2.5.3=h889cd5d_1
  - openssl=3.5.4=h5503f6c_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py311hdb8e4fa_1
  - pillow=11.3.0=py311h1f9957d_3
  - pip=25.2=pyhc872135_1
  - pthread-stubs=0.4=hd74edd7_1002
  - pycparser=2.22=pyh29332c3_1
  - pyparsing=3.2.5=pyhcf101f3_0
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.11.11=h89a136b_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.2.2=py3.11_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h80987f9_0
  - qhull=2020.2=h420ef59_5
  - readline=8.3=h0b18652_0
  - requests=2.32.5=pyhd8ed1ab_0
  - setuptools=80.9.0=py311hca03da5_0
  - six=1.17.0=pyhe01879c_1
  - sqlite=3.50.2=h79febb2_1
  - sympy=1.14.0=py311hca03da5_0
  - tk=8.6.15=hcd8a7d5_0
  - torchaudio=2.2.2=py311_cpu
  - torchvision=0.17.2=py311_cpu
  - tornado=6.5.2=py311h3696347_1
  - typing_extensions=4.15.0=py311hca03da5_0
  - tzdata=2025b=h04d1e81_0
  - unicodedata2=16.0.0=py311h3696347_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wheel=0.45.1=py311hca03da5_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - xz=5.6.4=h80987f9_1
  - yaml=0.2.5=h1a28f6b_0
  - zlib=1.3.1=h5f15de7_0
  - zstandard=0.25.0=py311h5bb9006_0
  - zstd=1.5.7=h6491c7d_2
  - pip:
      - cloudpickle==3.1.1
      - fsspec==2025.10.0
      - gym==0.26.2
      - gym-notices==0.1.0
      - numpy==2.2.6
      - opencv-python==4.12.0.88
      - polars==1.35.1
      - polars-runtime-32==1.35.1
      - psutil==7.1.2
      - scipy==1.16.3
      - ultralytics==8.3.223
      - ultralytics-thop==2.0.18
prefix: /opt/miniconda3/envs/my_env
